### ISSUE TITLE
url demo is not work

### ISSUE THREAD

**Issue by johnfelipe** [wbushey/Babble#14]
Not work

**Comment by Radcliffe** [comment]
Current demo URL is https://babble-gotmath.rhcloud.com/chat

**Comment by johnfelipe** [comment]
![screenshot_2015-05-01-13-22-06](https://cloud.githubusercontent.com/assets/428820/7435000/391b5930-f005-11e4-8573-711175c33741.png)
why repeat words?

**Comment by Radcliffe** [comment]
I don't know. I have not seen this behavior. Please describe your device, browser, and operating system, and I will look into it.
